version: '2'
services:
  seleniumhub:
    image: selenium/hub
    ports:
      - '9096:4444'
  firefoxnode:
    image: selenium/node-firefox-debug
    ports:
      - '5900'
    environment:
      - 'HUB_PORT_4444_TCP_ADDR=seleniumhub'
      - 'HUB_PORT_4444_TCP_PORT=4444'
    depends_on:
      - seleniumhub
  chromenode:
    image: selenium/node-chrome-debug
    ports:
      - '5900'
    environment:
      - 'HUB_PORT_4444_TCP_ADDR=seleniumhub'
      - 'HUB_PORT_4444_TCP_PORT=4444'
    depends_on:
      - seleniumhub
   
